version: '2'
services:
  craftcms:
    build: .
    environment:
      DB_SERVER: database
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: craft
      DB_PORT: 3306
      CRAFT_DEV_MODE: "true"
      SECURITY_KEY: hB9stszeyGNVaeoT2Pqu6dLAXruox
    links:
      - database
    ports:
      - "8881:80"
    volumes:
    - ./src/web:/var/www/web
    - ./src/templates:/var/www/templates
    - ./src/config:/var/www/config
    - ./src/modules:/var/www/modules

  database:
    image: webhippie/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USERNAME: craft
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: craft
    ports:
      - "3306:3306"
    volumes:
    - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8882:80
    links:
     - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password

volumes:
  data: