version: '2'
services:
  craftcms:
    build: .
    environment:
      CRAFT_DATABASE_HOST: database
      CRAFT_DATABASE_USER: craft
      CRAFT_DATABASE_PASSWORD: password
      CRAFT_DATABASE_NAME: craft
      CRAFT_DEV_MODE: "true"
    links:
      - database
    ports:
      - "8881:80"
    volumes:
    - ./src/web:/var/www/web
    - ./src/templates:/var/www/templates
    - ./src/plugins:/var/www/plugins
    - ./src/config:/var/www/config
    - ./src/modules:/var/www/modules

  database:
    image: webhippie/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USERNAME: craft
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: craft
    ports:
      - "3306:3306"
    volumes:
    - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8882:80
    links:
     - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password

volumes:
  data: